[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
upload_port = COM4          ; 改成你实际的端口号
monitor_port = COM4
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2@^1.5.0
    adafruit/Adafruit GFX Library
    olikraus/U8g2_for_Adafruit_GFX
    ; BLE uses built-in ESP32 Arduino BLE library (no extra dep needed)
; platformio.ini
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1